# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20171010_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
